# gitops/apps/llm-d-placement.yaml
# This RHACM resource defines a RULE for selecting clusters.
# We are selecting clusters that have the label "region=us-east".
# You would apply this label to your managed OpenShift clusters.
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: us-east-clusters
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          region: us-east