# gitops/manifests/llm-d-app/base/orchestrator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: llm-d-orchestrator
spec:
  selector:
    app: llm-d-orchestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080